Added token management
PushpalDev/base-api pull request #2
Opened 2017-06-01 07:31 UTC by dernise

2017-06-01 11:39 UTC, rb62680 submitted a review, later dismissed
J'ai mis un commentaire. Tu n'es pas obligé de changer mais dans ce cas tu peux répondre.

2017-06-01 11:39 UTC, rb62680 commented on models/user.go
> +func (user *User) HasToken(tokenId string) (int, bool) {
Tu pourrais juste envoyer un int et appeler la fonction getTokenId. Puis tu check si id = -1 et dans ce cas le user n'a pas le token. Si tu veux garder l'implémentation HasToken alors je préfère que tu renvoies d'abord le bool puis l'int. L'int étant un paramètre presque facultatif.

2017-06-01 11:44 UTC, dernise commented on models/user.go
> +func (user *User) HasToken(tokenId string) (int, bool) {
closed as primarily opinion-based by Maxence Henneron

2017-06-01 11:52 UTC, dernise commented on models/user.go
> +func (user *User) HasToken(tokenId string) (int, bool) {
Ne pas merge: Je dois aussi ajouter la fonction log out

2017-06-01 14:31 UTC, rb62680 commented on models/user.go
> +func (user *User) HasToken(tokenId string) (int, bool) {
@dernise Quand sera-t-elle dispo?

2017-06-01 14:32 UTC, dernise commented on models/user.go
> +func (user *User) HasToken(tokenId string) (int, bool) {
@rb62680 soon

2017-06-01 14:34 UTC, rb62680 commented on tests/helpers_test.go
> +	hashedPassword, _ := bcrypt.GenerateFromPassword([]byte(user.Password), bcrypt.DefaultCost)
@dernise On devrait créer un helper afin de ne pas répéter cette logique dans les tests et dans le controller

2017-06-01 14:35 UTC, rb62680 commented on models/token.go
> +type Token struct {
@dernise Devrait-elle s'appeler LoginToken?

2017-06-01 14:35 UTC, dernise commented on tests/helpers_test.go
> +	hashedPassword, _ := bcrypt.GenerateFromPassword([]byte(user.Password), bcrypt.DefaultCost)
Je trouve ça pas utile de creer un helper pour un code d'une ligne

2017-06-06 08:29 UTC, rb62680 requested changes
La route n'existe pas dans le routeur. Quelques modifications aussi sont necessaires.

2017-06-06 08:29 UTC, rb62680 commented on middlewares/auth.go
> +			c.AbortWithError(http.StatusUnauthorized, errors.New("LoginToken invalid"))
L'erreur n'est plus bonne

2017-06-06 08:29 UTC, rb62680 commented on models/user.go
> +	CurrentLoginToken string       `json:"-" bson:"-"`
Enleve

2017-06-06 08:29 UTC, rb62680 commented on store/context.go
> +	StoreKey      = "store"
Doit-il etre publique?

2017-06-06 08:29 UTC, rb62680 commented on store/mongodb/user.go
> +		return nil, helpers.NewError(http.StatusInternalServerError, "user_token_creation_failed", "Failed to create the token.")
Pour la consistence nos erreurs n'ont pas de points final

2017-06-06 08:29 UTC, rb62680 commented on store/store.go
> +	AddLoginToken(user *models.User, ip string) (*models.LoginToken, error)
Enleve le nom de l'attribut, juste son type

2017-06-07 15:21 UTC, rb62680 approved these changes

2017-06-07 15:59 UTC, merged